### ISSUE TITLE
Call `myCustomCommand` from JS

### ISSUE THREAD

**Issue by tcastelly** [tauri-apps/vue-cli-plugin-tauri#8]
I can't find something related to this in the [documentation](https://github.com/tauri-apps/tauri/wiki/11.-API). I'm pretty sure it's not a bug but I'm lost.

In the generated file `main.rs` there is a command that I should be able to run directly in my JavaScript.
It seems I have to use `tauri.invoke` and passing a JSON.

```json
 tauri.invoke({
    "cmd": {
      "myCustomCommand": ["toto"],
    }
 });
``` 

Of course it's not this ... 

I think generate a component, or use the HelloWorld to show how use this can be useful

**Comment by nothingismagick** [comment]
Thanks for the feedback! You're right - having the custom command prerigged would be great, as would having the emit / listen system setup and working.

@nklayman - can you look into this?

**Comment by nklayman** [comment]
The syntax for invoking a command is slightly different than your code snippet, use this instead:
```js
import tauri from 'tauri/api/tauri'
tauri.invoke({
  "cmd": 'myCustomCommand',
  argument: "toto",
});
```

Since it's pretty simple, I don't think it warrants its own component. However, maybe there should be a comment in the `main.rs` file with instructions on calling the default command with js, @nothingismagick what do you think about this?
